services:
  - type: web
    name: ai-ticket-reselling-2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    autoDeploy: true
    envVars: []
    region: frankfurt
    numInstances: 1
    runtimeEnvVars: []
    healthCheckPath: /health
    schedule:
      - cron: "*/10 * * * *"
        command: "python scraper.py"